# Generated by Django 5.2.3 on 2025-06-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
