# Generated by Django 5.2.3 on 2025-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_user_mediafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='file',
            field=models.FileField(default='existing_file.mp3', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='Existing_file.mp3', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
